import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "../components/layout/Navbar";
import AppProvider from "@/components/AppContext";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-5xl p-4 mx-auto">
          <AppProvider>
            <Navbar />
            {children}
            <footer className="text-center text-gray-600">
              &copy; 2024 all right reserved{" "}
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
